# Generated by Django 3.2.5 on 2021-07-22 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='period',
            field=models.DurationField(default=datetime.timedelta(seconds=21600)),
        ),
    ]
